### ISSUE TITLE
plugin does not recognise am/pm prefixes.

### ISSUE THREAD

**Issue by Errorcrafter** [SpoonMcForky/replace-timestamps-pc#2]
typing something like 3:30pm returns [timestamp for 3:30am]pm instead of the timestamp of 3:30pm. in addition, it only seems to recognise timestamps sent in the format xx:xx instead of xx.xx, which could lea to some confusion

**Comment by SpoonMcForky** [comment]
The plugin works essentially explicitly off of 24 hour time on purpose. I could add more cases and prefixes but I worry about message send times. I'll think about it but I won't guarantee anything.

**Comment by SpoonMcForky** [comment]
I've pushed some new code to the [dev](https://github.com/SpoonMcForky/replace-timestamps-pc/tree/dev) branch. This adds support for AM and PM suffixes, as well as custom prefixes in the settings. I haven't tested it extensively but I'm pretty sure it'll work without flaw.

**Comment by HelmicNewciv** [comment]
Looks like it works, but you'll want to probably factor in the possiblity of a sapce between the time and AM/PM as that's how a lot of people will naturally write it.

**Comment by SpoonMcForky** [comment]
I'll look into this when I can. I'm going to be away from my PC for a bit but I'll try my best.
