### ISSUE TITLE
Setting a prefix makes the plugin not function

### ISSUE THREAD

**Issue by 5h3i1ah** [SpoonMcForky/replace-timestamps-pc#4]
![image](https://user-images.githubusercontent.com/17099837/163733807-97925ba7-ebbd-47ef-9e90-2bcaec17b1c9.png)
When no prefix is set, I am perfectly able to send timestamps. However, when I add a prefix, using that prefix does not make timestamps, and (as expected) using no prefix also does not make a timestamp.

**Comment by SpoonMcForky** [comment]
I don't think it will work with multiple characters as a prefix. I mostly designed and planned for it to be a single character like $ or #. I'll check with the other issues later, currently not at my computer.

**Comment by 5h3i1ah** [comment]
![image](https://user-images.githubusercontent.com/17099837/163734588-64024aea-97e2-4c02-8f34-39c5be9c3f01.png)
Single letter prefix also seems to not work

**Comment by 5h3i1ah** [comment]
ah, single special characters work, gotcha. still a bit unintuitive, so i'd say it needs fixing.

**Comment by SpoonMcForky** [comment]
Hmm... I'll give it a look when I get home

**Comment by SpoonMcForky** [comment]
I found the root of the issue,I tested it with only the # character when developing it so other characters break it. I'll push something in a bit to fix it

**Comment by SpoonMcForky** [comment]
I just pushed a fix, let me know if there's anything wrong still.

**Comment by 5h3i1ah** [comment]
![image](https://user-images.githubusercontent.com/17099837/164563533-899e5026-719d-4123-88a2-bb3d0a5af07a.png)
Found some bugged cases. The prefix is working well though!
