### ISSUE TITLE
Formatting invalid timestamps, and incorrectly formatting some valid timestamps

### ISSUE THREAD

**Issue by 5h3i1ah** [SpoonMcForky/replace-timestamps-pc#8]
![image](https://user-images.githubusercontent.com/17099837/164563533-899e5026-719d-4123-88a2-bb3d0a5af07a.png)
Found some bugged cases. The prefix is working well though!

_Originally posted by @5h3i1ah in https://github.com/SpoonMcForky/replace-timestamps-pc/issues/4#issuecomment-1105831974_

Edit: And another one for the road!
![image](https://user-images.githubusercontent.com/17099837/164569545-54d9e69b-be87-4d06-abba-19c877a1c240.png)

**Comment by SpoonMcForky** [comment]
Alright, still not home yet but I'll be able to take a look in the coming days.
